# TODO:
# - https://github.com/sbarakat/beets-copyartifactso
# - https://github.com/nolsto/beets-follow

directory: ~/Music
library: ~/Music/library.db

# same as abcde
paths:
    default: $albumartist/$album%aunique{}/$track - $title
    singleton: $albumartist/$album%aunique{}/$title
    comp: Various/$album%aunique{}/$track - $artist  - $title
# don't always use original album release date
original_date: no
# don't use track numbers relative to disk
per_disc_numbering: no

import:
    # don't copy; move (copy ignored if move enabled anyway)
    copy: no
    move: yes
    # write metadata to songs
    write: yes
    # ask if want to resume previous halted session
    resume: ask
    # record imported directories and skip if try to import again?
    incremental: no
    # skip songs there is no recommendation for
    none_rec_action: skip
    # don't ask for confirmation for autotagging very close matches
    timid: no
    log: ~/Music/beetslog.txt

threaded: yes

plugins:
    fromfilename
    chroma
    fetchart
    lastgenre
    mpdupdate
    mpdstats
    lyrics
    keyfinder
    bpm

# will first check for images in folder importing
fetchart:
    auto: yes

lastgenre:
    source: track
    count: 4

# for use by mpdstats and mpdupdate
mpd:
    host: localhost
    port: 6600

lyrics:
    auto: no

keyfinder:
    auto: no

# vim:set softtabstop=4 shiftwidth=4 tabstop=4 expandtab:
